#!/bin/bash

declare -a POOL_NAMES
POOL_COUNT=0
declare -A OST_LIST
OST_COUNT=0

get_ostid()
{
	OSTID=$(trim_arg ${1})
	OSTID=`echo ${OSTID} | awk 'BEGIN {FS="(-OST)|(_UUID)"} { print $2 }'`
	OSTID=$((16#${OSTID}))
	if [[ "${OSTID}" -gt "${OST_COUNT}" ]]; then
		OST_COUNT=${OSTID}
	fi
}

#
# The config logs are just a list of each add/remove/etc. command
# They don't collapse pools that have been created, then deleted or OSTs
# that have been added/removed from those pools, so we need to keep
# track of the configuration as it evolves over time, so we only output
# the "current" configuration at the end.
#

parse_pool()
{
	ARGS=("${@}")
	POOLNAME=$(trim_arg ${ARGS[ (( 5 + ${SKIP} )) ]})

	case ${ARGS[ (( 2 + ${SKIP} )) ]} in
	*add*)
		get_ostid ${ARGS[ (( 6 + ${SKIP} )) ]}
		for i in `seq 0 ${POOL_COUNT}`; do
			if [[ "${OST_LIST[${OSTID},${i}]}" == '' ]]; then
				OST_LIST[${OSTID},${i}]=${POOLNAME}
				break
			fi
		done
		;;
	*remove*)
		get_ostid ${ARGS[ (( 6 + ${SKIP} )) ]}
		for i in `seq 0 ${POOL_COUNT}`; do
			if [[ "${OST_LIST[${OSTID},${i}]}" == "${POOLNAME}" ]]; then
				OST_LIST[${OSTID},${i}]=''
				break
			fi
		done

		;;
	*destroy*)
		for i in `seq 0 ${POOL_COUNT}`; do
			if [[ "${POOLNAME}" == "${POOL_NAMES[${i}]}" ]]; then
				POOL_NAMES[${i}]=''
				break
			fi
		done
		;;
	*new*)
		for i in `seq 0 ${POOL_COUNT}`; do
			if [ "${POOL_NAMES[${i}]}" == '' ]; then
				break
			fi
		done
		if [[ "${POOL_NAMES[${i}]}" == '' ]]; then
			POOL_NAMES[${i}]=${POOLNAME}
		else
			((POOL_COUNT++))
			POOL_NAMES[${POOL_COUNT}]=${POOLNAME}
		fi
		;;
	*)
		echo "bad pool argument"
		return
		;;
	esac
}

parse_param()
{
	return
}

LOCAL_DIR="$(dirname "${0}")"
if [ ! -d ${LOCAL_DIR} ]; then
	echo "${LOCAL_DIR} does not exist"
	exit
fi
. "${LOCAL_DIR}/params_main"

process_file "${FSNAME}-client"

# Print the commands to create the existing pools
for i in `seq 0 ${POOL_COUNT}`; do
	if [[ -n "${POOL_NAMES[${i}]}" ]]; then
		echo "lctl pool_new ${FSNAME}.${POOL_NAMES[${i}]}"
	fi
done

# Print the commands to add the proper OSTs to their pools
for j in `seq 0 ${OST_COUNT}`; do
	for k in `seq 0 ${POOL_COUNT}`; do
		if [[ -n "${OST_LIST[${j},${k}]}" ]]; then
			printf "lctl pool_add ${FSNAME}.${OST_LIST[$j,$k]} OST%04x\n" ${j}
		fi
	done
done
