#! /bin/bash
#
# lsvcgss      Lustre GSS daemon
#
# chkconfig: 2345 10 90
# description: start and stop the lsvcgssd daemon
#

# Source function library.
. /etc/init.d/functions

# See how we were called.
case "$1" in
        start)
                echo $"Starting lsvcgssd"
                /usr/sbin/lsvcgssd
                touch /var/lock/subsys/lsvcgssd
                ;;
        stop)
                echo $"Stopping lsvcgssd"
                killall lsvcgssd
                rm -f /var/lock/subsys/lsvcgssd
                ;;
  status)
        ;;
  restart|reload)
        $0 stop
        $0 start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac

exit 0
