#!/bin/bash

echo "=== Router Buffers ======="
VAR=$(lctl get_param buffers 2>&1)
if [ "${VAR/"error"}" = "$VAR" ] ; then
lctl get_param -n buffers
fi
echo
echo "=== NIs ============================================"
VAR=$(lctl get_param nis 2>&1)
if [ "${VAR/"error"}" = "$VAR" ] ; then
lctl get_param -n nis
fi
echo
echo "=== Peers ============================================================="
VAR=$(lctl get_param peers 2>&1)
if [ "${VAR/"error"}" = "$VAR" ] ; then
lctl get_param -n peers
fi
echo
