#!/bin/bash

echo "=== Router Buffers ======="
VAR=$(lctl get_param -n buffers 2>&1)
if [ $? = 0 ] ; then
	echo "$VAR"
fi
echo

echo "=== NIs ============================================"
VAR=$(lctl get_param -n nis 2>&1)
if [ $? = 0 ] ; then
	echo "$VAR"
fi
echo

echo "=== Peers ============================================================="
VAR=$(lctl get_param -n peers 2>&1)
if [ $? = 0 ] ; then
	echo "$VAR"
fi
echo
